version: '3.8'

services:
  webserver:
    image: development:latest
    container_name: development
    ports:
      - "5001:5001"
    volumes:
      - "./app:/app"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: imsdb
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
