version: '3.8'

services:
  webserver:
    image: production:latest
    container_name: production
    ports:
      - "5000:5001"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: imsdb
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
